### ISSUE TITLE
Educational ready?

### ISSUE THREAD

**Issue by dgutson** [openair-collective/openair-epiphyte#3]
Hi,

  Is epiphyte ready/mature to be a school project?
If so, could you please give me an estimate of the required budget?

**Comment by KCollins** [comment]
Epiphyte isn't yet ready to be an educational project, as it's still in a stage of active development. 

We recommend Cyan instead: https://github.com/openair-collective/openair-cyan
At the time of writing, Cyan's not currently being maintained, but can be copied or forked if you would like.
